#!/usr/bin/env bash
# Serve a web page using nginx
apt -y update
apt install -y nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default 
service nginx restart
