#!/usr/bin/env bash
# script that displays lines the file /etc/passwd
while IFS=: read -r username groupid home cmd userid pass useridinfo
do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $cmd. $userid's place is protected by the passcode $pass, more info about the user here: $useridinfo"
done < /etc/passwd