#!/usr/bin/env bash
#if, elif, else
x=1
while (( x<= 10))
do
    if ((x == 4))
    then
        echo "bad luck"
    elif ((x == 8))
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    ((x++))
done