#!/usr/bin/env bash
#count number 1 to 20
#count number 1 to 20
contador=1
termina=20
while [ $termina -ge $contador ]
do
  echo $contador
  case $contador in
      4)
         echo "bad luck from China"
      ;;
      9)
         echo "bad luck from Japan"
      ;;
      17)
         echo "bad luck from Italy"
      ;;
  esac
    ((contador++))
done
